# .streamlit/secrets.toml
SPREADSHEET_ID = "1VZcjZqVJW4c3TyM3X8ri6xX8prgRrUQ9avORDpwE2kw"

[gsheets_credentials]
type = "service_account"
project_id = "agroprint-database"
private_key_id = "2ac841913ffa41ce1fb01ca9b75d215e77c5a0dc"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCtDJCog/erzour
Fmq2YZrkOB+rw+JmAZ8e3IDRTggbZlfWguY7pxY+XIzNoZDI7bYrEcFSGK5oNeEM
7Q3B4dxWciemQZRuB2D4CZqbzN3LKY6GmuWH7xL2Vgt4Aj6f2g9/1m/hGpbJ3mmi
ZzNzV7lboNP38NRJZqIu4do9j+Ynw+PtonbMOpBfALYFHM+o23LngLH+HEoIbpWB
cQtEPnYVHy6TDuTdRQPCR91W6RKcP77yyJn9UC14B0n/SgsD8dSnG90hIq39cNAU
rIuCVIA9JwVcBly9mxi7EWp8yQQZ4ifkdpjb/xTR4p6KjdbZqtWR28osxEJNwwf9
naTNGOczAgMBAAECggEAEcJMr4Po4psuHt8MZoPPxy9co15VQ/iooXHUT9E9Pb/x
WxSl7LtHVMZfYNRS19FQCk171HavTLHdfbEaN1Um1+xGgLu8MCqBBhNzkseh1LFY
F3JFWf+Wp5ce/YWQHbbdiQCzDJvo8PXqoKhh/FVQCBo82/YSzdGYP/gc/d0LAUuK
t5qQzriVas3USNtEom+tZfV95KaY0YuJXDKlHYEqm+N5IPxbfDDNLxlFe9T9DLGI
1sJEwtQ3eL09tmNnQnGz6psyZLtPvuugm/8p7BuKYe8FOUE/DUKdXUsAeWPSKQ3S
I5FmxJC/6QQ0o7ER7njNRx1bJNdI6cbc4hERUS+CiQKBgQDqGxHpVTXTbI/klkUN
yLy5Zofx+mQkNJAFa5uiBr6AXYdkNIgnJza4m4gLJMXQHuepuiX+5SXguoWhnU2u
7q6H4qYJafidvSNTnkm7Xa6Swojo8JrjSdd4Sgz/h9lXwi4IUbJ0+4w/+blJ2BYU
ZJhSJQsVsWnaW/A2chbvYK58NwKBgQC9O68tgm9sff8ExElErzJvWGNLXvahLBLT
vwyqt0DLy3vwuCwBiBCM5yQiIx91OipwB1odI8Z8nNi3YYzMHxJpv0EFUIGt6Z5j
ZKT+yRnzaVWVAX9h6O9p40gT2niae6lLGk0XWvEBXJ3krmS3jPXzPrwXHw8gYjHG
DXnD6nmG5QKBgQCXh3YMhe8VLovk9a80wN4HU2pjIiN3m94s4/4U3jCofeGI5sfK
MAOncmSYcfDoSVjB749wcXoXACRG+76woCWwJvA537Hgx+/5y9cFxBmfPPPJcxOO
Utl5LtVDAPeZakLJd7f/KGMbddSNC6UfBg3h/cAzBmbxw9i0JRzbTMUj+QKBgAWf
L04f0OWdPKVMm4yh09LBAnorwRH6uDh4NY0g0pj7W5xELHKDM1KsT0OAXZ/i8X3Q
ihnRhUUQd9PC3yb1SVvA5dKdmKytAxqa09gJ625y06sQl1M2U16G9Q458FlOkTH8
/wtRlVVgBgTUNYPKeUgXtgjN0Go64JWsstBiN+gNAoGBAKwh+t+xytd203byMyDs
FFl79Y4suB1BQ/YpFiqpdi6kgKKGmtvRKH7Uqk50reoVIYXZcvVi8LDI2VT79H4g
ypwAanNnhynWbb+VjdY3r769nkWJwBvQS/Bxrk70UnDLtgVkvy+OsCAwPgC60prD
VVQlduYC6bK1qB5MTYkN9PG4
-----END PRIVATE KEY-----"""
client_email = "agroprint-service@agroprint-database.iam.gserviceaccount.com"
client_id = "117553127912533720234"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/agroprint-service%40agroprint-database.iam.gserviceaccount.com"
