# .streamlit/secrets.toml
SPREADSHEET_ID = "pon_aqui_tu_spreadsheet_id_real"

[gsheets_credentials]
type = "service_account"
project_id = "agroprint-database-123456"
private_key_id = "a1b2c3d4e5f67890abc123def456"
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCw...\n-----END PRIVATE KEY-----\n"
client_email = "agroprint-service@agroprint-database-123456.iam.gserviceaccount.com"
client_id = "123456789012345678901"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/agroprint-service%40agroprint-database-123456.iam.gserviceaccount.com"
